# declare the Visualize class
class Visualize:
    """
    This class contains a number of functions for dimensionality reduction and visualization of
    higher-dimensional datasets. It also contains a function to train a K-Means model on the 
    input data. The number of clusters that the K-Means model uses can be informed by the graphs 
    generated by the plot_2D and plot_3D functions - these can show the number of clusters in the 
    data. The dimensionality reduction functions, Reduce_Dim_PCA and Reduce_Dim_SVD, can be used 
    to reduce higher-dimensional datasets to 2D or 3D datasets that can then be graphed, for the 
    purpose of determining the number of clusters in the data, as outlined above.
    """
    
    # declare functions
    
    def train_k_means(self, X, n_clusters, init, n_init, max_iter, tolerance):
        """
        This function trains a k-means clustering model, using the scikit-learn package.
        Documentation: http://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
        
        Variables:
        X: features to be clustered (integer array - 2D, where each row is a datapoint and each column is a feature)
        n_clusters: the number of clusters to form as well as the number of centroids to generate
        init: the method for initialization - see link above
        n_init: the number of time the k-means algorithm will be run with different centroid seeds
        max_iter: the maximum number of iterations of the k-means algorithm for a single run
        tolerance: the relative tolerance with regards to inertia to declare convergence
        """
        
        # import the required Python packages
        from sklearn.cluster import KMeans
        
        # declare k-means model object
        K_Means = KMeans(n_clusters, init, n_init, max_iter, tolerance, precompute_distances='auto', verbose=0, random_state=None, copy_x=True, n_jobs=1, algorithm='auto')
        
        # train model
        K_Means.fit(X)
        
        # return trained K-Means model
        return K_Means;
        
    def Reduce_Dim_PCA(self, X, num_components, num_plot_components): 
        """
        This function uses PCA to reduce the dimensionality of a 2D matrix, X, and then uses T-SNE to further reduce the dimensionality of this matrix, for the purpose of plotting/visualization
        Documentation (PCA): http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.PCA.html
        Documentation (T-SNE):http://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html
        
        Variables:
        X: 2D integer array - this is the input data
        num_components: the number of components to which we will reduce the matrix X, using PCA
        num_plot_components: the number of components to which we shall further reduce the resulting PCA-reduced-dimensionality array, using T-SNE, for the purpose of plotting/visualization.
        """
        
        # import the required Python packages
        import numpy as np
        import pandas as pd
        from sklearn import manifold
        from sklearn.decomposition import PCA
        
        # ensure that the number of components for PCA dimensionality reduction is greater than or equal to the number of plot/T-SNE components
        if (num_components >= num_plot_components):
            
            # ensure that the number of plot/T-SNE components is either 2 or 3
            if ((num_plot_components == 2) or (num_plot_components == 3)):
                
                # declare PCA object
                pca = PCA(n_components = num_components)
                
                # get PCA reduced-dimensionality matrix
                principalComponents = pca.fit_transform(X)
                
                # declare T-SNE object
                tsne = manifold.TSNE(n_components = num_plot_components, init='random', random_state=0)
                
                # get T-SNE reduced-dimensionality matrix
                X_tsne = tsne.fit_transform(principalComponents)
                
                # check if the plot should be 2D or 3D - declare a pandas dataframe of the T-SNE reduced-dimensionality data accordingly
                if num_plot_components == 2:
                    # declare 2D pandas dataframe
                    plot_Data = pd.DataFrame(X_tsne, columns = ['principal component 1', 'principal component 2'])
                else:
                    # declare 3D pandas dataframe
                    plot_Data = pd.DataFrame(X_tsne, columns = ['principal component 1', 'principal component 2', 'principal component 3'])
            else:
                # raise error
                raise ValueError("The variable: num_plot_components must be equal to either 2 or 3")
        else:
            # raise error
            raise ValueError("The varable: num_components must be greater than num_plot_components")
        
        # return both the PCA reduced-dimensionality matrix and the T-SNE reduced-dimensionality matrix
        return principalComponents, plot_Data;
    
    def Reduce_Dim_SVD(self, X, num_components, num_plot_components): 
        """
        This function uses SVD to reduce the dimensionality of a sparse 2D matrix, X, and then uses T-SNE to further reduce the dimensionality of this matrix, for the purpose of plotting/visualization.
        This function is used to reduce the dimensionality of sparse matrices, which is useful for applications such as Natural Language Processing - for example, the dimensionality reduction of TF-IDF matrices.
        Documentation (SVD): http://scikit-learn.org/stable/modules/generated/sklearn.decomposition.TruncatedSVD.html
        Documentation (T-SNE):http://scikit-learn.org/stable/modules/generated/sklearn.manifold.TSNE.html
        
        Variables:
        X: 2D integer array - this is the input data
        num_components: the number of components to which we will reduce the matrix X, using SVD
        num_plot_components: the number of components to which we shall further reduce the resulting SVD-reduced-dimensionality array, using T-SNE, for the purpose of plotting/visualization
        """
        
        # import the required Python packages
        import numpy as np
        import pandas as pd
        from sklearn import manifold
        from sklearn.decomposition import TruncatedSVD
        
        # ensure that the number of components for SVD dimensionality reduction is greater than or equal to the number of plot/T-SNE components
        if (num_components >= num_plot_components):
            
            # ensure that the number of plot/T-SNE components is either 2 or 3
            if ((num_plot_components == 2) or (num_plot_components == 3)):
                
                # declare SVD object
                svd = TruncatedSVD(n_components = num_components)
                
                # get SVD reduced-dimensionality matrix
                principalComponents = svd.fit_transform(X)
                
                # declare T-SNE object
                tsne = manifold.TSNE(n_components = num_plot_components, init='random', random_state=0)
                
                # get T-SNE reduced-dimensionality matrix
                X_tsne = tsne.fit_transform(principalComponents)
                
                # check if the plot should be 2D or 3D - declare a pandas dataframe of the T-SNE reduced-dimensionality data accordingly
                if num_plot_components == 2:
                    # declare 2D pandas dataframe
                    plot_Data = pd.DataFrame(X_tsne, columns = ['principal component 1', 'principal component 2'])
                else:
                    # declare 3D pandas dataframe
                    plot_Data = pd.DataFrame(X_tsne, columns = ['principal component 1', 'principal component 2', 'principal component 3'])
            else:
                # raise error
                raise ValueError("The variable: num_plot_components must be equal to either 2 or 3")
        else:
            # raise error
            raise ValueError("The varable: num_components must be greater than num_plot_components")
        
        # return both the SVD reduced-dimensionality matrix and the T-SNE reduced-dimensionality matrix
        return principalComponents, plot_Data;
    
    # function to produce zoomed in scatter plot of pandas data frame data in 2D
    def plot_2D(self, principalDf):
        """
        This function produces an interactive 2D plot of a pandas dataframe.
        Documentation: https://matplotlib.org/index.html
        
        Variables:
        principalDf: a 2D pandas dataframe with integer values, and two columns: 'principal component 1' and 'principal component 2'.
        """
        
        # declare interactive matplotlib notebook
        %matplotlib notebook
        
        # declare 2D graph object
        graph2d = plt.figure().gca(projection='2d')
        
        # set labels of the graph axes
        graph2d.set_xlabel('Principal Component 1')
        graph2d.set_ylabel('Principal Component 2')
        
        # plot the dataframe values on the 2D graph
        graph2d.scatter(df['principal component 1'],df['principal component 2'])
        
        return;
    
    # function to produce zoomed in scatter plot of pandas data frame data in 3D
    def plot_3D(self, principalDf):
        """
        This function produces an interactive 3D plot of a pandas dataframe.
        Documentation: https://matplotlib.org/index.html
        
        Variables:
        principalDf: a 3D pandas dataframe with integer values, and two columns: 'principal component 1', 'principal component 2' and 'principal component 3'.
        """
        
        # declare interactive matplotlib notebook
        %matplotlib notebook
        
        # declare 3D graph object
        graph3d = plt.figure().gca(projection='3d')
        
        # set labels of the graph axes
        graph3d.set_xlabel('Principal Component 1')
        graph3d.set_ylabel('Principal Component 2')
        graph3d.set_zlabel('Principal Component 3')
        
        # plot the dataframe values on the 3D graph
        graph3d.scatter(df['principal component 1'],df['principal component 2'],df['principal component 3'])
        
        return;
